language: python

python:
  - "3.6"

addons:
  postgresql: "9.6"

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput
  - py.test

after_success:
  - coveralls
