language: python

python:
  - "3.6"

addons:
  postgresql: "9.6"

  before_script:
    - psql -c "CREATE DATABASE ireporter;" -U postgres

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test

after_success:
  - coveralls
